### ISSUE TITLE
NumberFormatException in Event.getConfigurationVersion()

### ISSUE THREAD

**Issue by ollie-dev** [ollie-dev/innogy-API-client-library#2]
`17:10:37.166 [ERROR] [marthome.handler.InnogyBridgeHandler] - Error with Event: {}
       at in.ollie.innogysmarthome.entity.event.Event.getConfigurationVersion(Event.java:335)java.lang.NumberFormatException: For input string: "1039.0"

       at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)[:1.8.0_65]
       at org.openhab.binding.innogysmarthome.handler.InnogyBridgeHandler.onEvent(InnogyBridgeHandler.java:439)
       at java.lang.Integer.parseInt(Integer.java:580)[:1.8.0_65]
       at org.openhab.binding.innogysmarthome.internal.InnogyWebSocket.onMessage(InnogyWebSocket.java:62)      at java.lang.Integer.parseInt(Integer.java:615)[:1.8.0_65]

       at in.ollie.innogysmarthome.entity.PropertyList.getPropertyValueAsInteger(PropertyList.java:110)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at in.ollie.innogysmarthome.entity.event.Event.getConfigurationVersion(Event.java:335)
       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       at org.openhab.binding.innogysmarthome.handler.InnogyBridgeHandler.onEvent(InnogyBridgeHandler.java:439)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at org.openhab.binding.innogysmarthome.internal.InnogyWebSocket.onMessage(InnogyWebSocket.java:62)
       at java.lang.reflect.Method.invoke(Method.java:497)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[:1.8.0_65]
       at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:71)
       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)[:1.8.0_65]
       at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:72)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.8.0_65]
       at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.onTextMessage(JettyAnnotatedEventDriver.java:234)     at java.lang.reflect.Method.invoke(Method.java:497)[:1.8.0_65]

       at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:71)[203:org.openhab.binding.inno      at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69)gysmarthome:2.0.0.201611132234]

       at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:72      at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:66))[203:org.openhab.binding.innogysmarthome:2.0.0.201611132234]

       at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.onTextMessage(JettyAnnotatedEventDriver.java:234)[203:or      at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.onTextFrame(JettyAnnotatedEventDriver.java:226)g.openhab.binding.innogysmarthome:2.0.0.201611132234]

       at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69)[203:org.openhab.bind      at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:162)ing.innogysmarthome:2.0.0.201611132234]

       at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:66)[203:org.openhab.bin      at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:376)ding.innogysmarthome:2.0.0.201611132234]

       at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.onTextFrame(JettyAnnotatedEventDriver.java:226)[203:org.      at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:220)openhab.binding.innogysmarthome:2.0.0.201611132234]

       at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)       at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:162)[203:org.openhab.bi
nding.innogysmarthome:2.0.0.201611132234]
       at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:256)
       at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:376)[203:org.openhab.binding.innogys      at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:679)marthome:2.0.0.201611132234]

       at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:220)[203:org.openhab.binding.      at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:511)innogysmarthome:2.0.0.201611132234]

       at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)[203:org.openhab.binding.innogysmarthome:2.0.0.2016111      at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)32234]

       at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:256)[203:org.openhab.binding.innogysmarthome:2.0.0.201611132234]      at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)

       at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:679)[203:org.op      at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:202)enhab.binding.innogysmarthome:2.0.0.201611132234]

       at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:511)[203:org.o      at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)penhab.binding.innogysmarthome:2.0.0.201611132234]

       at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)[203:org.openhab.binding.innogysm      at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)arthome:2.0.0.201611132234]

       at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)[203:org.openhab.binding.innogysmarthome:2.0.0.201611132234]
       at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)      at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:202)[203:org.openhab.binding.innogysmarthome:2.0.0.201611132234]

       at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)[203:org.openhab.binding.innogysm      at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)arthome:2.0.0.201611132234]

       at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)[203:org.openhab.binding.innogysmarthome:2.0.0.201611132234]      at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)

       at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)[203:org.openhab.binding.innogysmarthome:2.0.      at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)0.201611132234]

       at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)[203:org.o      at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)penhab.binding.innogysmarthome:2.0.0.201611132234]

       at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)[203:org.openhab.      at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)binding.innogysmarthome:2.0.0.201611132234]

       at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)[203:org.openhab.binding.inn      at java.lang.Thread.run(Thread.java:745)ogysmarthome:2.0.0.201611132234]

       at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)[203:org.openhab.binding.innogysmarthome:2.0.0.201611132234]
       at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)[203:org.openhab.binding.innogysmarthome:2.0.0.201611132234]
       at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]`

Maybe still handles as Integer?

**Comment by ollie-dev** [comment]
fixed with a1395e5
